#!/usr/bin/env python3
#by Josh Brown
# This is a networking script.The point of this script is to read an excel document for IP addresses and ensure the routers associated with the address are using the updated configure file. If not, it will update them.

#imports
import napalm
import xlrd
from napalm import get_network_driver

#Function to get read ip adddresses and login
iplist = []
wb = xlrd.open_workbook('/home/student/mycode/python_practice.xlsx') #opens
# get the first worksheet
first_sheet = wb.sheet_by_index(0)

def login(ipadd):
#loop to call all values in row x column 1 of workbook and populate them into list ip.
    for ips in range(0, first_sheet.nrows):
        x = first_sheet.col_values(0,1,ips)
        driver = get_network_driver('eos')
        device = driver(ips, 'admin', 'alta3') #applies a universal login and pssw
        device.open #device logon command
    iplist.extend(x)

login(iplist)
print(iplist)

user = input('what is your universal login? ')
password = input("what is the universal password ? ")


#for loop to login to a router and then to compare and/or configure the routres
for fix in iplist:
    #configfile = o('configuration', 'rb')
    driver = get_network_driver('eos')
    device = driver(fix, user, password) #applies a universal login and pssw
    device.open() #device logon command

    device.load_replace_candidate(filename='/home/student/mycode/configuration') #file path has to be the file you wish to load onto your device
    print(device.compare_config())
    #device.compare.config(config) #compares config.txt on the machines to t#he one on file
    device.commit_config()
    device.close()
