#!/usr/bin/env python3

#imports
import random

#This is a board game. Every player rolls a dice from 1-12 first to 100 wins
#By Josh Brown

from random import randint

#ask for number of players, creates a dic for every player
num_player = input("How many will be playing Dicequest?(2-6 players) ")
num_players =int(num_player) + 1  #allows me to start numbering players at 1 instead of 0

#takes the input value from user and turns it into an append list
list_players = []
for x in range(1, num_players):
    list_players.append('Player ' + str(x))
print(list_players)

mylist = []


## creating dictionaries with proper strcutures
for x in range(len(list_players)):
    dic = {'name': list_players[x], 'score' : 0}
    mylist.append(dic)
print(mylist)


##dice roll code 
min = 1 
max = 6

## while loop that will increase the players score with a dice roll function until score 100 is met

##I need a way to call the name value first and then roll the dice
## use a for loop with a +1 to cycle through values of 'name'

win=False
while win != True:
    for turn in range(len(list_players)):
        roll= (random.randint(min, max))
        print(mylist[turn]['name'] + ' rolled ' + str(roll))
        mylist[turn]['score'] += roll #(random.randint(min, max))
        print(mylist[turn]['name'] + ' is at ' + str(mylist[turn]['score']))
        
        if mylist[turn]['score'] >= 15:
            print('The winner is ' + mylist[turn]['name'] + ' with a score of ' + str(mylist[turn]['score']) + '!')
            win = True
            break


